# config/packages/knp_snappy.yaml
knp_snappy:
    pdf:
        enabled: true
        binary: '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:
            encoding: UTF-8
        
    image:
        enabled: true
        binary: '%kernel.project_dir%/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64'
        options: []