controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

register:
  path: '/register'
  methods:  [POST]
  controller: App\Controller\RegistrationController::register

api_login:
  path: '/login'
  methods:  [POST]
  controller: App\Controller\ApiLoginController::index

api_verify_email:
  path: '/verify/email'
  methods:  [POST]
  controller: App\Controller\RegistrationController::verifyUserEmail