controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

register:
  path: '/register'
  methods:  [POST]
  controller: App\Controller\RegistrationController::register

api_login:
  path: '/login'
  methods:  [POST]
  controller: App\Controller\ApiLoginController::index

api_verify_email:
  path: '/verify/email'
  methods:  [POST]
  controller: App\Controller\RegistrationController::verifyUserEmail

api_send_email:
  path: '/send/email'
  methods:  [POST]
  controller: App\Controller\EmailController::sendEmail

api_send_booking_email:
  path: '/send/bookingEmail'
  methods:  [POST]
  controller: App\Controller\EmailController::sendBookingEmail

api_update_element_position:
  path: '/sections/{id}/position'
  methods:  [PUT]
  controller: App\Controller\WebController::updatePosition

api_print_pdf:
  path: '/print_pdf'
  methods:  [POST]
  controller: App\Controller\DocumentController::pdfAction

api_list_hotels:
  path: '/list_hotels'
  methods:  [POST]
  controller: App\Controller\IntegrationController::listHotels