# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'es'
    availableLocales:
        - 'en'
        - 'de'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $parametersAvailableLocales: '%availableLocales%'
            $parametersDefaultLocale: '%locale%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\UserController:
        arguments:
            - '@lexik_jwt_authentication.jwt_manager'
            - '@security.token_storage'
    
    App\EventListener\JWTResponseListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    # Gedmo\Translatable\TranslatableListener:
    #     alias: stof_doctrine_extensions.listener.translatable
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
